// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lshvobwypxlvksmtyzln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzaHZvYnd5cHhsdmtzbXR5emxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTkyMzcsImV4cCI6MjA2Mjk5NTIzN30.cN_flNH8xsRPGb55RO9_bgbe8zApFWaROy1oGDrDwe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);