// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://comzekipeqxdbppfkwac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbXpla2lwZXF4ZGJwcGZrd2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzYwNjMsImV4cCI6MjA2MjY1MjA2M30.OSHF_V5YKTWp3cB7awC-izobiathVs-_XB8dsB0aPXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);